swagger: '2.0'
info:
  title: backend service
  description: Сервис для управления ПВЗ и приемкой товаров
  version: 1.0.0

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Token:
    type: string

  User:
    type: object
    properties:
      id:
        type: string
        format: uuid
      email:
        type: string
        format: email
      role:
        type: string
        enum: [employee, moderator]
    required: [email, role]

  PVZ:
    type: object
    properties:
      id:
        type: string
        format: uuid
      registrationDate:
        type: string
        format: date-time
      city:
        type: string
        enum: [Москва, Санкт-Петербург, Казань]
    required: [city]

  Reception:
    type: object
    properties:
      id:
        type: string
        format: uuid
      dateTime:
        type: string
        format: date-time
      pvzId:
        type: string
        format: uuid
      status:
        type: string
        enum: [in_progress, close]
    required: [dateTime, pvzId, status]

  Product:
    type: object
    properties:
      id:
        type: string
        format: uuid
      dateTime:
        type: string
        format: date-time
      type:
        type: string
        enum: [электроника, одежда, обувь]
      receptionId:
        type: string
        format: uuid
    required: [type, receptionId]

  Error:
    type: object
    properties:
      message:
        type: string
    required: [message]

paths:
  /dummyLogin:
    post:
      summary: Получение тестового токена
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              role:
                type: string
                enum: [employee, moderator]
            required: [role]
      responses:
        200:
          description: Успешная авторизация
          schema:
            $ref: '#/definitions/Token'
        400:
          description: Неверный запрос
          schema:
            $ref: '#/definitions/Error'

  /register:
    post:
      summary: Регистрация пользователя
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
              password:
                type: string
              role:
                type: string
                enum: [employee, moderator]
            required: [email, password, role]
      responses:
        201:
          description: Пользователь создан
          schema:
            $ref: '#/definitions/User'
        400:
          description: Неверный запрос
          schema:
            $ref: '#/definitions/Error'

  /login:
    post:
      summary: Авторизация пользователя
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
              password:
                type: string
            required: [email, password]
      responses:
        200:
          description: Успешная авторизация
          schema:
            $ref: '#/definitions/Token'
        401:
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/Error'

  /pvz:
    post:
      summary: Создание ПВЗ (только для модераторов)
      security:
        - bearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/PVZ'
      responses:
        201:
          description: ПВЗ создан
          schema:
            $ref: '#/definitions/PVZ'
        400:
          description: Неверный запрос
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'

    get:
      summary: Получение списка ПВЗ с фильтрацией по дате приемки и пагинацией
      security:
        - bearerAuth: []
      parameters:
        - name: startDate
          in: query
          required: false
          type: string
          format: date-time
        - name: endDate
          in: query
          required: false
          type: string
          format: date-time
        - name: page
          in: query
          required: false
          type: integer
          minimum: 1
          default: 1
        - name: limit
          in: query
          required: false
          type: integer
          minimum: 1
          maximum: 30
          default: 10
      responses:
        200:
          description: Список ПВЗ
          schema:
            type: array
            items:
              type: object
              properties:
                pvz:
                  $ref: '#/definitions/PVZ'
                receptions:
                  type: array
                  items:
                    type: object
                    properties:
                      reception:
                        $ref: '#/definitions/Reception'
                      products:
                        type: array
                        items:
                          $ref: '#/definitions/Product'

  /pvz/{pvzId}/close_last_reception:
    post:
      summary: Закрытие последней открытой приемки товаров в рамках ПВЗ
      security:
        - bearerAuth: []
      parameters:
        - name: pvzId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: Приемка закрыта
          schema:
            $ref: '#/definitions/Reception'
        400:
          description: Неверный запрос или приемка уже закрыта
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'

  /pvz/{pvzId}/delete_last_product:
    post:
      summary: Удаление последнего добавленного товара из текущей приемки (LIFO, только для сотрудников ПВЗ)
      security:
        - bearerAuth: []
      parameters:
        - name: pvzId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: Товар удален
        400:
          description: Неверный запрос, нет активной приемки или нет товаров для удаления
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'

  /receptions:
    post:
      summary: Создание новой приемки товаров (только для сотрудников ПВЗ)
      security:
        - bearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              pvzId:
                type: string
                format: uuid
            required: [pvzId]
      responses:
        201:
          description: Приемка создана
          schema:
            $ref: '#/definitions/Reception'
        400:
          description: Неверный запрос или есть незакрытая приемка
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'

  /products:
    post:
      summary: Добавление товара в текущую приемку (только для сотрудников ПВЗ)
      security:
        - bearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              type:
                type: string
                enum: [электроника, одежда, обувь]
              pvzId:
                type: string
                format: uuid
            required: [type, pvzId]
      responses:
        201:
          description: Товар добавлен
          schema:
            $ref: '#/definitions/Product'
        400:
          description: Неверный запрос или нет активной приемки
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Доступ запрещен
          schema:
            $ref: '#/definitions/Error'