// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPvzOKCode is the HTTP code returned for type GetPvzOK
const GetPvzOKCode int = 200

/*
GetPvzOK Список ПВЗ

swagger:response getPvzOK
*/
type GetPvzOK struct {

	/*
	  In: Body
	*/
	Payload []*GetPvzOKBodyItems0 `json:"body,omitempty"`
}

// NewGetPvzOK creates GetPvzOK with default headers values
func NewGetPvzOK() *GetPvzOK {

	return &GetPvzOK{}
}

// WithPayload adds the payload to the get pvz o k response
func (o *GetPvzOK) WithPayload(payload []*GetPvzOKBodyItems0) *GetPvzOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pvz o k response
func (o *GetPvzOK) SetPayload(payload []*GetPvzOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPvzOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetPvzOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
