// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostPvzPvzIDCloseLastReceptionHandlerFunc turns a function with the right signature into a post pvz pvz ID close last reception handler
type PostPvzPvzIDCloseLastReceptionHandlerFunc func(PostPvzPvzIDCloseLastReceptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPvzPvzIDCloseLastReceptionHandlerFunc) Handle(params PostPvzPvzIDCloseLastReceptionParams) middleware.Responder {
	return fn(params)
}

// PostPvzPvzIDCloseLastReceptionHandler interface for that can handle valid post pvz pvz ID close last reception params
type PostPvzPvzIDCloseLastReceptionHandler interface {
	Handle(PostPvzPvzIDCloseLastReceptionParams) middleware.Responder
}

// NewPostPvzPvzIDCloseLastReception creates a new http.Handler for the post pvz pvz ID close last reception operation
func NewPostPvzPvzIDCloseLastReception(ctx *middleware.Context, handler PostPvzPvzIDCloseLastReceptionHandler) *PostPvzPvzIDCloseLastReception {
	return &PostPvzPvzIDCloseLastReception{Context: ctx, Handler: handler}
}

/*
	PostPvzPvzIDCloseLastReception swagger:route POST /pvz/{pvzId}/close_last_reception postPvzPvzIdCloseLastReception

Закрытие последней открытой приемки товаров в рамках ПВЗ
*/
type PostPvzPvzIDCloseLastReception struct {
	Context *middleware.Context
	Handler PostPvzPvzIDCloseLastReceptionHandler
}

func (o *PostPvzPvzIDCloseLastReception) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostPvzPvzIDCloseLastReceptionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
