// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostReceptionsHandlerFunc turns a function with the right signature into a post receptions handler
type PostReceptionsHandlerFunc func(PostReceptionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostReceptionsHandlerFunc) Handle(params PostReceptionsParams) middleware.Responder {
	return fn(params)
}

// PostReceptionsHandler interface for that can handle valid post receptions params
type PostReceptionsHandler interface {
	Handle(PostReceptionsParams) middleware.Responder
}

// NewPostReceptions creates a new http.Handler for the post receptions operation
func NewPostReceptions(ctx *middleware.Context, handler PostReceptionsHandler) *PostReceptions {
	return &PostReceptions{Context: ctx, Handler: handler}
}

/*
	PostReceptions swagger:route POST /receptions postReceptions

Создание новой приемки товаров (только для сотрудников ПВЗ)
*/
type PostReceptions struct {
	Context *middleware.Context
	Handler PostReceptionsHandler
}

func (o *PostReceptions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostReceptionsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostReceptionsBody post receptions body
//
// swagger:model PostReceptionsBody
type PostReceptionsBody struct {

	// pvz Id
	// Required: true
	// Format: uuid
	PvzID *strfmt.UUID `json:"pvzId"`
}

// Validate validates this post receptions body
func (o *PostReceptionsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePvzID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostReceptionsBody) validatePvzID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"pvzId", "body", o.PvzID); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"pvzId", "body", "uuid", o.PvzID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post receptions body based on context it is used
func (o *PostReceptionsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostReceptionsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostReceptionsBody) UnmarshalBinary(b []byte) error {
	var res PostReceptionsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
