// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostPvzPvzIDDeleteLastProductParams creates a new PostPvzPvzIDDeleteLastProductParams object
//
// There are no default values defined in the spec.
func NewPostPvzPvzIDDeleteLastProductParams() PostPvzPvzIDDeleteLastProductParams {

	return PostPvzPvzIDDeleteLastProductParams{}
}

// PostPvzPvzIDDeleteLastProductParams contains all the bound params for the post pvz pvz ID delete last product operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostPvzPvzIDDeleteLastProduct
type PostPvzPvzIDDeleteLastProductParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	PvzID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostPvzPvzIDDeleteLastProductParams() beforehand.
func (o *PostPvzPvzIDDeleteLastProductParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPvzID, rhkPvzID, _ := route.Params.GetOK("pvzId")
	if err := o.bindPvzID(rPvzID, rhkPvzID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPvzID binds and validates parameter PvzID from path.
func (o *PostPvzPvzIDDeleteLastProductParams) bindPvzID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("pvzId", "path", "strfmt.UUID", raw)
	}
	o.PvzID = *(value.(*strfmt.UUID))

	if err := o.validatePvzID(formats); err != nil {
		return err
	}

	return nil
}

// validatePvzID carries on validations for parameter PvzID
func (o *PostPvzPvzIDDeleteLastProductParams) validatePvzID(formats strfmt.Registry) error {

	if err := validate.FormatOf("pvzId", "path", "uuid", o.PvzID.String(), formats); err != nil {
		return err
	}
	return nil
}
