// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/totorialman/go-task-avito/models"
)

// PostProductsCreatedCode is the HTTP code returned for type PostProductsCreated
const PostProductsCreatedCode int = 201

/*
PostProductsCreated Товар добавлен

swagger:response postProductsCreated
*/
type PostProductsCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewPostProductsCreated creates PostProductsCreated with default headers values
func NewPostProductsCreated() *PostProductsCreated {

	return &PostProductsCreated{}
}

// WithPayload adds the payload to the post products created response
func (o *PostProductsCreated) WithPayload(payload *models.Product) *PostProductsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post products created response
func (o *PostProductsCreated) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProductsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostProductsBadRequestCode is the HTTP code returned for type PostProductsBadRequest
const PostProductsBadRequestCode int = 400

/*
PostProductsBadRequest Неверный запрос или нет активной приемки

swagger:response postProductsBadRequest
*/
type PostProductsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostProductsBadRequest creates PostProductsBadRequest with default headers values
func NewPostProductsBadRequest() *PostProductsBadRequest {

	return &PostProductsBadRequest{}
}

// WithPayload adds the payload to the post products bad request response
func (o *PostProductsBadRequest) WithPayload(payload *models.Error) *PostProductsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post products bad request response
func (o *PostProductsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProductsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostProductsForbiddenCode is the HTTP code returned for type PostProductsForbidden
const PostProductsForbiddenCode int = 403

/*
PostProductsForbidden Доступ запрещен

swagger:response postProductsForbidden
*/
type PostProductsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostProductsForbidden creates PostProductsForbidden with default headers values
func NewPostProductsForbidden() *PostProductsForbidden {

	return &PostProductsForbidden{}
}

// WithPayload adds the payload to the post products forbidden response
func (o *PostProductsForbidden) WithPayload(payload *models.Error) *PostProductsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post products forbidden response
func (o *PostProductsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProductsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
