// Code generated by go-swagger; DO NOT EDIT.

// Package restapi backend service
//
//	Сервис для управления ПВЗ и приемкой товаров
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
