// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Token token
//
// swagger:model Token
type Token string

// Validate validates this token
func (m Token) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this token based on context it is used
func (m Token) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
